apiVersion: v1
kind: Service
metadata:
  name: dynamic-certs
  labels:
    app: dynamic-certs
spec:
  ports:
    - port: 443 
      targetPort: 443 
      name: https
  selector:
    app: dynamic-certs
  type: LoadBalancer
